### ISSUE TITLE
首页个人信息部分 CSS 样式问题

### ISSUE THREAD

**Issue by fuchao2012** [awesomes-cn/awesomes#20]
换行了。

建议参考 github css。

或者好好参考 😂

**Comment by bimohxh** [comment]
具体指的哪一部分的样式呢

**Comment by fuchao2012** [comment]
sorry 没说清楚。

![screen shot 2016-11-15 at 16 02 08](https://cloud.githubusercontent.com/assets/5637185/20297727/e667aa22-ab4c-11e6-9df4-ba5c7e99f410.jpg)

左边换行了

**Comment by bimohxh** [comment]
谢谢反馈，没处理好响应式布局
