### ISSUE TITLE
请问rank页面的背景效果怎么做的

### ISSUE THREAD

**Issue by iamwelk** [awesomes-cn/awesomes#25]
是用了什么库吗

**Comment by iamwelk** [comment]
图片贴不上去，是那个随机出现小球和连线的效果

**Comment by bimohxh** [comment]
都是开源的，代码在这里 https://github.com/awesomes-cn/new-awesomes/blob/master/pages/rank.vue

**Comment by iamwelk** [comment]
看到了，谢谢！
