### ISSUE TITLE
awesomes 很喜欢，有没有一些需要帮忙的，想贡献一些力量

### ISSUE THREAD

**Issue by lihlio** [awesomes-cn/awesomes#4]
刚才代码看了一下，可以加上一些键盘事件，这样在翻页的时候就不用再去点击下部的分页链接

**Comment by awesomes-cn** [comment]
谢谢支持，如果你能贡献代码，我们非常高兴，也可以给我们多多提建议和意见

**Comment by lihlio** [comment]
我给你回消息了，好像没你没有看到。我已经修改了部分代码。待我发一些邮件给你，我先关闭这个卡了
